[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    https://github.com/HomeSpan/HomeSpan.git#master
    https://github.com/miguelbalboa/rfid.git#master
build_flags =
    -DCORE_DEBUG_LEVEL=3
