[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM5
monitor_port = COM5
board_build.partitions = min_spiffs.csv
lib_deps =
    https://github.com/HomeSpan/HomeSpan.git#2.1.6
    https://github.com/miguelbalboa/rfid.git#1.4.12
build_flags =
    -DCORE_DEBUG_LEVEL=3
