[platformio]
default_envs = esp32c3

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/miguelbalboa/rfid.git#1.4.12

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM6
monitor_port = COM6
lib_deps =
    https://github.com/miguelbalboa/rfid.git#1.4.12
